services:
  - type: web
    name: assignmate-backend
    env: node
    plan: free
    root: assignmate/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
